### ISSUE TITLE
Replace grunt :/

### ISSUE THREAD

**Issue by codfish** [andy-spotting/www#17]
trying to assign to @peterghintz but i can't

basically since we have a nice clean slate in an app like this i think it would be cool to use another tool that we don't use all the time. I'm also sick of grunt, especially in coordination with sass cause that shit is slow as balls.

Thoughts? theres always make, which for a small project like this might be nice (might be able to compile sass directly using `sassc` https://github.com/sass/sassc). but then there's grunt alternatives like gulp and some others

lets sexy it up

**Comment by aj-may** [comment]
will be closed by https://github.com/andy-spotting/www/pull/18

**Comment by aj-may** [comment]
closed by #18
